export const topStocks = [
  {
    id: 1,
    name: "Apple Inc.",
    symbol: "AAPL",
    price: 178.72,
    change: 2.34,
    changePercent: 1.32,
    marketCap: "2.8T",
    volume: "78.9M",
    sector: "Technology",
    logo: "https://logo.clearbit.com/apple.com",
  },
  {
    id: 2,
    name: "Microsoft Corporation",
    symbol: "MSFT",
    price: 338.11,
    change: -1.23,
    changePercent: -0.36,
    marketCap: "2.5T",
    volume: "45.2M",
    sector: "Technology",
    logo: "https://logo.clearbit.com/microsoft.com",
  },
  {
    id: 3,
    name: "Tesla, Inc.",
    symbol: "TSLA",
    price: 238.45,
    change: 5.67,
    changePercent: 2.44,
    marketCap: "756.8B",
    volume: "125.3M",
    sector: "Automotive",
    logo: "https://logo.clearbit.com/tesla.com",
  },
  {
    id: 4,
    name: "NVIDIA Corporation",
    symbol: "NVDA",
    price: 410.68,
    change: -1.61,
    changePercent: -0.39,
    marketCap: "3.7T",
    volume: "20.5M",
    sector: "Technology",
    logo: "https://logo.clearbit.com/nvidia.com",
  },
  {
    id: 5,
    name: "Amazon.com, Inc.",
    symbol: "AMZN",
    price: 145.31,
    change: -0.56,
    changePercent: -0.38,
    marketCap: "1.5T",
    volume: "35.6M",
    sector: "Consumer Discretionary",
    logo: "https://logo.clearbit.com/amazon.com",
  },
  {
    id: 6,
    name: "Berkshire Hathaway Inc.",
    symbol: "BRK.B",
    price: 451.31,
    change: -0.19,
    changePercent: -0.04,
    marketCap: "974.98B",
    volume: "3.1M",
    sector: "Financials",
    logo: "https://logo.clearbit.com/berkshirehathaway.com",
  },
  {
    id: 7,
    name: "Meta Platforms, Inc.",
    symbol: "META",
    price: 300.12,
    change: 1.23,
    changePercent: 0.41,
    marketCap: "798B",
    volume: "18M",
    sector: "Communication Services",
    logo: "https://logo.clearbit.com/meta.com",
  },
  {
    id: 8,
    name: "Alphabet Inc.",
    symbol: "GOOGL",
    price: 1500.25,
    change: -2.15,
    changePercent: -0.14,
    marketCap: "1.9T",
    volume: "1M",
    sector: "Communication Services",
    logo: "https://logo.clearbit.com/alphabet.com",
  },
  {
    id: 9,
    name: "UnitedHealth Group Incorporated",
    symbol: "UNH",
    price: 503.56,
    change: -0.84,
    changePercent: -0.17,
    marketCap: "463B",
    volume: "3M",
    sector: "Healthcare",
    logo: "https://logo.clearbit.com/unitedhealthgroup.com",
  },
  {
    id: 10,
    name: "Exxon Mobil Corporation",
    symbol: "XOM",
    price: 107.26,
    change: 1.42,
    changePercent: 1.34,
    marketCap: "471B",
    volume: "12M",
    sector: "Energy",
    logo: "https://logo.clearbit.com/exxonmobil.com",
  },
  {
    id: 11,
    name: "Eli Lilly and Company",
    symbol: "LLY",
    price: "765.47",
    change: "1.",
    changePercent: "0.",
    marketCap: "689B",
    volume: "4M",
    sector: "Healthcare",
    logo: "https://logo.clearbit.com/lilly.com",
  },
  {
    id: 12,
    name: "JPMorgan Chase & Co.",
    symbol: "JPM",
    price: "239.20",
    change: "-.05",
    changePercent: "-.02",
    marketCap: "673B",
    volume: "7M",
    sector: "Financials",
    logo: "https://logo.clearbit.com/jpmorgan.com",
  },
  {
    id: 13,
    name: "Visa Inc.",
    symbol: "V",
    price: "315.69",
    change: "0.",
    changePercent: "0.",
    marketCap: "618B",
    volume: "6M",
    sector: "Financials",
    logo: "https://logo.clearbit.com/visa.com",
  },
  {
    id: 14,
    name: "Mastercard Incorporated",
    symbol: "MA",
    price: "526.35",
    change: "0.",
    changePercent: "0.",
    marketCap: "483B",
    volume: "4M",
    sector: "Financials",
    logo: "https://logo.clearbit.com/mastercard.com",
  },
  {
    id: 15,
    name: "The Procter & Gamble Company",
    symbol: "PG",
    price: "166.70",
    change: "-.24",
    changePercent: "-.14",
    marketCap: "392B",
    volume: "5M",
    sector: "Consumer Staples",
    logo: "https://logo.clearbit.com/pg.com",
  },
  {
    id: 16,
    name: "Walmart Inc.",
    symbol: "WMT",
    price: "90.19",
    change: "-.42",
    changePercent: "-.46",
    marketCap: "724B",
    volume: "10M",
    sector: "Consumer Staples",
    logo: "https://logo.clearbit.com/walmart.com",
  },
  {
    id: 17,
    name: "Costco Wholesale Corporation",
    symbol: "COST",
    price: "914.48",
    change: "-.84",
    changePercent: "-.09",
    marketCap: "405B",
    volume: "2M",
    sector: "Consumer Staples",
    logo: "https://logo.clearbit.com/costco.com",
  },
  {
    id: 18,
    name: "Chevron Corporation",
    symbol: "CVX",
    price: "144.60",
    change: "1." + "07",
    changePercent: "0." + "81%",
    marketCap: "259B",
    volume: "4M",
    sector: "Energy",
    logo: "https://logo.clearbit.com/chevron.com",
  },
  {
    id: 19,
    name: "Home Depot, Inc.",
    symbol: "HD",
    price: "387",
    change: "-0",
    changePercent: "-0",
    marketCap: "385",
    volume: "3",
    sector: "Consumer Services",
    logo: "https://logo.clearbit.com/homedepot.com",
  },
  {
    id: 20,
    name: "Pfizer Inc.",
    symbol: "PFE",
    price: "43",
    change: "-0",
    changePercent: "-0",
    marketCap: "241",
    volume: "8",
    sector: "Healthcare",
    logo: "https://logo.clearbit.com/pfizer.com",
  },
];
