export const stocksAndTickers = [
  { name: "Apple Inc.", ticker: "AAPL" },
  { name: "Microsoft Corporation", ticker: "MSFT" },
  { name: "Amazon.com, Inc.", ticker: "AMZN" },
  { name: "Alphabet Inc. (Class A)", ticker: "GOOGL" },
  { name: "Alphabet Inc. (Class C)", ticker: "GOOG" },
  { name: "Tesla, Inc.", ticker: "TSLA" },
  { name: "Meta Platforms, Inc.", ticker: "META" },
  { name: "NVIDIA Corporation", ticker: "NVDA" },
  { name: "Berkshire Hathaway Inc. (Class B)", ticker: "BRK.B" },
  { name: "JPMorgan Chase & Co.", ticker: "JPM" },
  { name: "Johnson & Johnson", ticker: "JNJ" },
  { name: "Visa Inc.", ticker: "V" },
  { name: "Walmart Inc.", ticker: "WMT" },
  { name: "Procter & Gamble Company", ticker: "PG" },
  { name: "UnitedHealth Group Incorporated", ticker: "UNH" },
  { name: "Home Depot, Inc.", ticker: "HD" },
  { name: "Mastercard Incorporated", ticker: "MA" },
  { name: "Bank of America Corporation", ticker: "BAC" },
  { name: "Walt Disney Company", ticker: "DIS" },
  { name: "PayPal Holdings, Inc.", ticker: "PYPL" },
  { name: "Intel Corporation", ticker: "INTC" },
  { name: "Verizon Communications Inc.", ticker: "VZ" },
  { name: "AT&T Inc.", ticker: "T" },
  { name: "Coca-Cola Company", ticker: "KO" },
  { name: "Pfizer Inc.", ticker: "PFE" },
  { name: "Nike, Inc.", ticker: "NKE" },
  { name: "Chevron Corporation", ticker: "CVX" },
  { name: "PepsiCo, Inc.", ticker: "PEP" },
  { name: "Netflix, Inc.", ticker: "NFLX" },
  { name: "Adobe Inc.", ticker: "ADBE" },
  { name: "Salesforce.com Inc.", ticker: "CRM" },
  { name: "Cisco Systems, Inc.", ticker: "CSCO" },
  { name: "Exxon Mobil Corporation", ticker: "XOM" },
  { name: "Wells Fargo & Company", ticker: "WFC" },
  { name: "McDonald's Corporation", ticker: "MCD" },
  { name: "AbbVie Inc.", ticker: "ABBV" },
  { name: "Oracle Corporation", ticker: "ORCL" },
  { name: "Thermo Fisher Scientific Inc.", ticker: "TMO" },
  { name: "Broadcom Inc.", ticker: "AVGO" },
  { name: "Accenture plc", ticker: "ACN" },
  { name: "United Parcel Service, Inc.", ticker: "UPS" },
  { name: "Morgan Stanley", ticker: "MS" },
  { name: "Honeywell International Inc.", ticker: "HON" },
  { name: "Medtronic plc", ticker: "MDT" },
  { name: "Union Pacific Corporation", ticker: "UNP" },
  { name: "QUALCOMM Incorporated", ticker: "QCOM" },
  { name: "Texas Instruments Incorporated", ticker: "TXN" },
  { name: "Bristol-Myers Squibb Company", ticker: "BMY" },
  { name: "Goldman Sachs Group, Inc.", ticker: "GS" },
  { name: "Starbucks Corporation", ticker: "SBUX" },
  { name: "3M Company", ticker: "MMM" },
  { name: "Caterpillar Inc.", ticker: "CAT" },
  { name: "Eli Lilly and Company", ticker: "LLY" },
  { name: "American Express Company", ticker: "AXP" },
  { name: "Lockheed Martin Corporation", ticker: "LMT" },
  { name: "General Electric Company", ticker: "GE" },
  { name: "Ford Motor Company", ticker: "F" },
  { name: "Boeing Company", ticker: "BA" },
  { name: "IBM", ticker: "IBM" },
  { name: "Target Corporation", ticker: "TGT" },
  { name: "General Motors Company", ticker: "GM" },
  { name: "Citigroup Inc.", ticker: "C" },
  { name: "Dow Inc.", ticker: "DOW" },
  { name: "HP Inc.", ticker: "HPQ" },
  { name: "Uber Technologies, Inc.", ticker: "UBER" },
  { name: "Lyft, Inc.", ticker: "LYFT" },
  { name: "Snap Inc.", ticker: "SNAP" },
  { name: "Square, Inc.", ticker: "SQ" },
  { name: "Zoom Video Communications, Inc.", ticker: "ZM" },
  { name: "Pinterest, Inc.", ticker: "PINS" },
  { name: "Palantir Technologies Inc.", ticker: "PLTR" },
  { name: "Roku, Inc.", ticker: "ROKU" },
  { name: "Moderna, Inc.", ticker: "MRNA" },
  { name: "Snowflake Inc.", ticker: "SNOW" },
  { name: "Airbnb, Inc.", ticker: "ABNB" },
  { name: "DoorDash, Inc.", ticker: "DASH" },
  { name: "Coinbase Global, Inc.", ticker: "COIN" },
  { name: "Robinhood Markets, Inc.", ticker: "HOOD" },
  { name: "Lucid Group, Inc.", ticker: "LCID" },
  { name: "Rivian Automotive, Inc.", ticker: "RIVN" },
  { name: "GameStop Corp.", ticker: "GME" },
  { name: "AMC Entertainment Holdings, Inc.", ticker: "AMC" },
  { name: "Bed Bath & Beyond Inc.", ticker: "BBBY" },
  { name: "BlackBerry Limited", ticker: "BB" },
  { name: "Tilray, Inc.", ticker: "TLRY" },
  { name: "Canopy Growth Corporation", ticker: "CGC" },
  { name: "Aurora Cannabis Inc.", ticker: "ACB" },
  { name: "Sundial Growers Inc.", ticker: "SNDL" },
  { name: "Beyond Meat, Inc.", ticker: "BYND" },
  { name: "Virgin Galactic Holdings, Inc.", ticker: "SPCE" },
  { name: "DraftKings Inc.", ticker: "DKNG" },
];
